apiVersion: batch/v1
kind: Job
metadata:
  name: osworld
  namespace: inference-benchmark
  labels:
    app: osworld
    component: evaluation
spec:
  ttlSecondsAfterFinished: 86400  # Clean up after 24 hours (evaluations can be long)
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: osworld
        component: evaluation
    spec:
      restartPolicy: Never
      # OSWorld requires desktop environments - may need privileged mode or specific node selectors
      # Consider using nodes with GPU support if available
      containers:
      - name: osworld-eval
        image: ghcr.io/hyperboliclabs/osworld:latest
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "=== OSWorld Evaluation ==="
          
          # Start Docker daemon (required for Docker provider in containerd/cri-o clusters)
          echo "Starting Docker daemon..."
          
          # Create Docker data directory
          mkdir -p /var/lib/docker
          
          # Start dockerd in background with proper configuration
          dockerd \
            --host=unix:///var/run/docker.sock \
            --storage-driver=vfs \
            --data-root=/var/lib/docker \
            > /tmp/dockerd.log 2>&1 &
          DOCKERD_PID=$!
          
          # Wait for Docker daemon to be ready
          echo "Waiting for Docker daemon to start..."
          timeout=60
          while [ $timeout -gt 0 ]; do
            if docker info >/dev/null 2>&1; then
              echo "✅ Docker daemon is ready"
              docker info | head -5
              break
            fi
            sleep 1
            timeout=$((timeout - 1))
            if [ $((timeout % 10)) -eq 0 ]; then
              echo "Still waiting... ($timeout seconds remaining)"
            fi
          done
          
          if [ $timeout -eq 0 ]; then
            echo "❌ Docker daemon failed to start after 60 seconds"
            echo "Docker daemon logs:"
            cat /tmp/dockerd.log
            exit 1
          fi
          
          # Run evaluation (includes Datadog export)
          cd /osworld
          python3 run_evaluation.py
          
          # Cleanup: stop Docker daemon
          kill $DOCKERD_PID 2>/dev/null || true
        env:
        # Inference endpoint configuration
        - name: OPENAI_BASE_URL
          value: "http://infra-inference-scheduling-inference-gateway.llm-d.svc.cluster.local/v1"
        - name: OPENAI_API_KEY
          value: "dummy-key"
        - name: MODEL_NAME
          value: "Qwen/Qwen3-VL-32B-Thinking"
        
        # OSWorld configuration
        - name: PROVIDER_NAME
          value: "docker"  # Options: docker, aws, virtualbox, vmware, azure, aliyun
        - name: NUM_ENVS
          value: "1"  # Number of parallel environments
        - name: MAX_STEPS
          value: "15"  # Maximum steps per task
        - name: MAX_TOKENS
          value: "32768"  # Maximum tokens per request
        - name: DOMAIN
          value: "all"  # Domain to test (or specific domain)
        - name: TEST_META_PATH
          value: "evaluation_examples/test_nogdrive.json"
        - name: RESULT_DIR
          value: "/osworld/results"
        - name: ACTION_SPACE
          value: "pyautogui"
        - name: OBSERVATION_TYPE
          value: "screenshot"
        - name: ADDITIONAL_ARGS
          value: ""  # Additional arguments for run_multienv_qwen3vl.py
        # Datadog API key for metrics export (optional)
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-api-key
              key: api-key
              optional: true
        
        # Datadog LLM Observability configuration
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        - name: DD_LLMOBS_ENABLED
          value: "1"
        - name: DD_LLMOBS_ML_APP
          value: "osworld-benchmark"
        - name: DD_SITE
          value: "us5.datadoghq.com"
        
        # Desktop environment may require privileged access
        securityContext:
          privileged: true  # Required for Docker provider
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
        
        volumeMounts:
        - name: results
          mountPath: /osworld/results
        # Docker socket mount removed - cluster uses containerd/cri-o
        # OSWorld will need to use a different provider or run in privileged mode
        resources:
          requests:
            memory: "8Gi"
            cpu: "2000m"
          limits:
            memory: "16Gi"
            cpu: "4000m"
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: osworld-results
          # Optional: Use emptyDir for ephemeral results
          # emptyDir: {}
      # Docker socket volume removed - cluster uses containerd
      imagePullSecrets:
      - name: ghcr-image-pull-secret
