apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiperf-results
  namespace: inference-benchmark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gcore-nfs-3ab538e0-f64d-47bf-a72a-4fa646944598
